{
  "http": {
    "port": ${PORT:-8090}
  },

  "apiEndpoints": {

    "api": {
      "host": "*", #localhost - poner "*" cuando se va a desplegar a produccion
      "paths": '/ip'
    },
    "inventario": {
      "host": "*", #localhost - poner "*" cuando se va a desplegar a produccion
      "paths": "/api_inventario/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    },
    "tienda": {
      "host": "*",
      "paths":  "/api_tienda/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    },
    "administracion": {
      "host": "*",
      "paths":  "/api_administracion/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    }

  },
  "serviceEndpoints": {

    "api": {
      "url": "https://httpbin.org"
    },

    "inventario": {
      "url": "http://127.0.0.1:8000"
    },
    "tienda": {
      "url": "http://localhost:8001"
    },
    "administracion": {
      "url": "http://localhost:8002"
    }

  },
  "policies": [
    "basic-auth",
    "key-auth",
    "cors",
    "expression",
    "log",
    "oauth2",
    "proxy",
    "rate-limit"
  ],
  "pipelines": [
  {
    "name": "default",
    "apiEndpoints": [
      "inventario"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "inventario",
          "changeOrigin": true
        }
      }
      ]
    }
    ]
  },
  {
    "name": "default-1",
    "apiEndpoints": [
      "tienda"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "tienda"
        }
      }
      ]
    }
    ]
  },
  {
    "name": "default-2",
    "apiEndpoints": [
      "administracion"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "administracion"
        }
      }
      ]
    }
    ]
  },
  {
    "name": "default-3",
    "apiEndpoints": [
      "api"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "api",
          "changeOrigin": true
        }
      }
      ]
    }
    ]
  }
  ]
}
