{
  "http": {
    "port": ${HTTP_PORT:-8090}
  },
  "admin": {
    "port": 9876,
    "hostname": "localhost"
  },
  "apiEndpoints": {

    "inventario": {
      "host": "localhost",
      "paths": "/api_inventario/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    },
    "tienda": {
      "host": "localhost",
      "paths":  "/api_tienda/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    },
    "administracion": {
      "host": "localhost",
      "paths":  "/api_administracion/*",
      "methods": ["GET", "PUT", "POST", "PATCH", "DELETE"]
    }

  },
  "serviceEndpoints": {

    "inventario": {
      "url": "http://localhost:8000"
    },
    "tienda": {
      "url": "http://localhost:8001"
    },
    "administracion": {
      "url": "http://localhost:8002"
    }

  },
  "policies": [
    "basic-auth",
    "key-auth",
    "cors",
    "expression",
    "log",
    "oauth2",
    "proxy",
    "rate-limit"
  ],
  "pipelines": [
  {
    "name": "default",
    "apiEndpoints": [
      "inventario"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "inventario"
        }
      }
      ]
    }
    ]
  },
  {
    "name": "default-1",
    "apiEndpoints": [
      "tienda"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "tienda"
        }
      }
      ]
    }
    ]
  },
  {
    "name": "default-2",
    "apiEndpoints": [
      "administracion"
    ],
    "policies": [
    {
      "proxy": [
      {
        "action": {
          "serviceEndpoint": "administracion"
        }
      }
      ]
    }
    ]
  }
  ]
}
